// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jan 2021 16:01:54 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package vulkan provides Go bindings for vulkan.h
*/
package vulkan
